# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cricket.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog, QLineEdit, QMessageBox, QDialog, QPushButton, QTableWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(950, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.aboveframe = QtWidgets.QFrame(self.centralwidget)
        self.aboveframe.setFrameShape(QtWidgets.QFrame.Box)
        self.aboveframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.aboveframe.setLineWidth(2)
        self.aboveframe.setObjectName("aboveframe")
        self.aboveLayout = QtWidgets.QVBoxLayout(self.aboveframe)
        self.aboveLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.aboveLayout.setContentsMargins(10, 5, 10, 20)
        self.aboveLayout.setSpacing(20)
        self.aboveLayout.setObjectName("aboveLayout")
        self.label = QtWidgets.QLabel(self.aboveframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.aboveLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.aboveframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_batsmen = QtWidgets.QLabel(self.aboveframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_batsmen.sizePolicy().hasHeightForWidth())
        self.label_batsmen.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label_batsmen.setFont(font)
        self.label_batsmen.setObjectName("label_batsmen")
        self.horizontalLayout_2.addWidget(self.label_batsmen)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.aboveframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_bowlers = QtWidgets.QLabel(self.aboveframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bowlers.sizePolicy().hasHeightForWidth())
        self.label_bowlers.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label_bowlers.setFont(font)
        self.label_bowlers.setObjectName("label_bowlers")
        self.horizontalLayout_2.addWidget(self.label_bowlers)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.aboveframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_allrounders = QtWidgets.QLabel(self.aboveframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_allrounders.sizePolicy().hasHeightForWidth())
        self.label_allrounders.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label_allrounders.setFont(font)
        self.label_allrounders.setObjectName("label_allrounders")
        self.horizontalLayout_2.addWidget(self.label_allrounders)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.aboveframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_wicketkeeper = QtWidgets.QLabel(self.aboveframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_wicketkeeper.sizePolicy().hasHeightForWidth())
        self.label_wicketkeeper.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label_wicketkeeper.setFont(font)
        self.label_wicketkeeper.setObjectName("label_wicketkeeper")
        self.horizontalLayout_2.addWidget(self.label_wicketkeeper)
        self.aboveLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.aboveframe)
        spacerItem4 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 0, -1, -1)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.label_ptsavail = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_ptsavail.setFont(font)
        self.label_ptsavail.setObjectName("label_ptsavail")
        self.horizontalLayout_4.addWidget(self.label_ptsavail)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, 10, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 9, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_bat = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_bat.sizePolicy().hasHeightForWidth())
        self.radio_bat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.radio_bat.setFont(font)
        self.radio_bat.setObjectName("radio_bat")
        self.horizontalLayout.addWidget(self.radio_bat)
        self.radio_bow = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_bow.sizePolicy().hasHeightForWidth())
        self.radio_bow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.radio_bow.setFont(font)
        self.radio_bow.setObjectName("radio_bow")
        self.horizontalLayout.addWidget(self.radio_bow)
        self.radio_ar = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_ar.sizePolicy().hasHeightForWidth())
        self.radio_ar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.radio_ar.setFont(font)
        self.radio_ar.setObjectName("radio_ar")
        self.horizontalLayout.addWidget(self.radio_ar)
        self.radio_wk = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_wk.sizePolicy().hasHeightForWidth())
        self.radio_wk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.radio_wk.setFont(font)
        self.radio_wk.setObjectName("radio_wk")
        self.horizontalLayout.addWidget(self.radio_wk)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.list_playersavail = QtWidgets.QListWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_playersavail.sizePolicy().hasHeightForWidth())
        self.list_playersavail.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.list_playersavail.setFont(font)
        self.list_playersavail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_playersavail.setFrameShadow(QtWidgets.QFrame.Plain)
        self.list_playersavail.setObjectName("list_playersavail")
        self.verticalLayout.addWidget(self.list_playersavail)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem10)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.label_ptsused = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_ptsused.setFont(font)
        self.label_ptsused.setObjectName("label_ptsused")
        self.horizontalLayout_7.addWidget(self.label_ptsused)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(10, -1, 10, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_teamname = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_teamname.sizePolicy().hasHeightForWidth())
        self.label_teamname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.label_teamname.setFont(font)
        self.label_teamname.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_teamname.setObjectName("label_teamname")
        self.horizontalLayout_5.addWidget(self.label_teamname)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.list_playersused = QtWidgets.QListWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_playersused.sizePolicy().hasHeightForWidth())
        self.list_playersused.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.list_playersused.setFont(font)
        self.list_playersused.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_playersused.setFrameShadow(QtWidgets.QFrame.Plain)
        self.list_playersused.setObjectName("list_playersused")
        self.verticalLayout_4.addWidget(self.list_playersused)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        spacerItem15 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuManage_Teams.sizePolicy().hasHeightForWidth())
        self.menuManage_Teams.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.menuManage_Teams.setFont(font)
        self.menuManage_Teams.setTearOffEnabled(False)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionOPEN_Team = QtWidgets.QAction(MainWindow)
        self.actionOPEN_Team.setObjectName("actionOPEN_Team")
        self.actionEDIT_Team = QtWidgets.QAction(MainWindow)
        self.actionEDIT_Team.setObjectName("actionEDIT_Team")
        self.actionEVALUATE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUATE_Team.setObjectName("actionEVALUATE_Team")
        self.menuManage_Teams.addAction(self.actionNEW_Team)
        self.menuManage_Teams.addAction(self.actionOPEN_Team)
        self.menuManage_Teams.addAction(self.actionEDIT_Team)
        self.menuManage_Teams.addSeparator()
        self.menuManage_Teams.addAction(self.actionEVALUATE_Team)
        self.menubar.addAction(self.menuManage_Teams.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # window title
        MainWindow.setWindowTitle('Fantasy Cricket')

        # setting label colors
        self.label_batsmen.setStyleSheet('color: blue')
        self.label_bowlers.setStyleSheet('color: blue')
        self.label_allrounders.setStyleSheet('color: blue')
        self.label_wicketkeeper.setStyleSheet('color: blue')
        self.label_ptsavail.setStyleSheet('color: orange')
        self.label_ptsused.setStyleSheet('color: orange')
        self.label_teamname.setStyleSheet('color: green')

        # disabling of radio buttons
        self.radio_bat.setDisabled(True)
        self.radio_bow.setDisabled(True)
        self.radio_ar.setDisabled(True)
        self.radio_wk.setDisabled(True)

        # menu buttons
        self.menuManage_Teams.triggered[QtWidgets.QAction].connect(self.menufunction)

        # connection with database
        self.db = sqlite3.connect("Cricket.db")
        self.cur = self.db.cursor()

        # connection of radiofuction
        self.radio_bat.clicked.connect(self.radiofuction)
        self.radio_bow.clicked.connect(self.radiofuction)
        self.radio_ar.clicked.connect(self.radiofuction)
        self.radio_wk.clicked.connect(self.radiofuction)

        self.list_playersavail.itemDoubleClicked.connect(self.listwidgetfuction)
        self.list_playersused.itemDoubleClicked.connect(self.playerRemove)

    def playerRemove(self, item):
        print(item.text)
        self.list_playersused.takeItem(self.list_playersused.row(item))
        self.listPopulate()
        self.pointsUsedFunction()
        self.categoryLabelCount()

    def listwidgetfuction(self, item):
        print(item.text())
        self.cur.execute('SELECT Value from Stats WHERE Player = "' + item.text() + '"')
        b = self.cur.fetchone()
        if self.radio_wk.isChecked() == True and self.label_wicketkeeper.text() == "1":
            QMessageBox.warning(MainWindow, "Warning", "Cannot add more than 1 wicketkeeper")
        elif len(self.list_playersused.findItems(item.text(),
                                                 QtCore.Qt.MatchExactly)) == 0 and self.list_playersused.count() < 11:
            if int(self.label_ptsavail.text()) > int(b[0]):
                self.list_playersused.addItem(item.text())
                self.list_playersused.sortItems()
                self.listPopulate()
                self.pointsUsedFunction()
            else:
                QMessageBox.warning(MainWindow, "Warning", "You do not have enough points")
        else:
            QMessageBox.warning(MainWindow, "Warning", "Cannot add more than 11 players")
        self.categoryLabelCount()

    def listPopulate(self):
        self.list_playersavail.clear()
        for n in self.list:
            if len(self.list_playersused.findItems(n[0], QtCore.Qt.MatchExactly)) == 0:
                self.list_playersavail.addItem(n[0])
        self.list_playersavail.sortItems()

    def menufunction(self, action):
        txt = (action.text())
        print(txt)
        if txt == 'NEW Team':
            print('new')
            self.getTeamname()
        if txt == 'OPEN Team':
            print('open')
            self.openDialog()
        if txt == 'SAVE Team':
            print('save')
            if self.list_playersused.count() == 11:
                if self.label_wicketkeeper.text() == "1":
                    self.saveTeamList()
                    self.db.commit()
                    QMessageBox.information(MainWindow, "Info", "Team Saved Successfully")
                else:
                    QMessageBox.information(MainWindow, "Info", "Team has no wicketkeeper")
            else:
                print("No Team Created")
                QMessageBox.information(MainWindow, "Info", "Team Incomplete")
        if txt == 'EVALUATE Team':
            print('evaluate')
            self.evalDialog()

    def radiofuction(self):
        if self.radio_bat.isChecked() == True:
            print("radio_bat")
            self.cur.execute("SELECT Player from Stats WHERE Ctg = 'BAT'")
            self.list = self.cur.fetchall()
            print(self.list)

        elif self.radio_bow.isChecked() == True:
            print("radio_bow")
            self.cur.execute("SELECT Player from Stats WHERE Ctg = 'BWL'")
            self.list = self.cur.fetchall()
            print(self.list)

        elif self.radio_ar.isChecked() == True:
            print("radio_ar")
            self.cur.execute("SELECT Player from Stats WHERE Ctg = 'AR'")
            self.list = self.cur.fetchall()
            print(self.list)

        elif self.radio_wk.isChecked() == True:
            print("radio_wk")
            self.cur.execute("SELECT Player from Stats WHERE Ctg = 'WK'")
            self.list = self.cur.fetchall()
            print(self.list)

        self.listPopulate()

    def getTeamname(self):
        self.tname = QInputDialog.getText(MainWindow, "Team Name", "Enter the name of the team:", QLineEdit.Normal, "")
        if self.tname[0] != "" and self.tname[1] == True:
            print(self.tname)
            # enable radio buttons
            self.radio_bat.setEnabled(True)
            self.radio_bat.setChecked(True)
            self.radio_bow.setEnabled(True)
            self.radio_ar.setEnabled(True)
            self.radio_wk.setEnabled(True)
            # setting labels count to 0
            self.label_batsmen.setText("0")
            self.label_bowlers.setText("0")
            self.label_allrounders.setText("0")
            self.label_wicketkeeper.setText("0")
            self.label_ptsused.setText("0")
            # calling radio function
            self.radiofuction()
            # set points available and teamname
            self.label_ptsavail.setText("1000")
            self.label_teamname.setText(self.tname[0])
        else:
            print("Team Name not entered")

    def categoryLabelCount(self):
        if self.label_ptsused.text() != "0":
            # category label count
            count = (len(self.list) - self.list_playersavail.count())
            if self.radio_bat.isChecked() == True:
                self.label_batsmen.setText(str(count))
                print("bat " + str(count))

            elif self.radio_bow.isChecked() == True:
                self.label_bowlers.setText(str(count))
                print("bow " + str(count))

            elif self.radio_ar.isChecked() == True:
                self.label_allrounders.setText(str(count))
                print("ar " + str(count))

            elif self.radio_wk.isChecked() == True:
                self.label_wicketkeeper.setText(str(count))
                print("wk " + str(count))
        else:
            self.label_batsmen.setText("0")
            self.label_bowlers.setText("0")
            self.label_allrounders.setText("0")
            self.label_wicketkeeper.setText("0")

    def saveTeamList(self):
        players = ""
        for x in range(self.list_playersused.count()):
            players = players + (self.list_playersused.item(x).text() + ",")
        print(players)
        self.cur.execute('INSERT INTO Teams (Name, Players, Value) VALUES ("' + self.tname[
            0] + '","' + players + '","' + self.label_ptsused.text() + '")')

    def pointsUsedFunction(self):
        self.value = 0
        for x in range(self.list_playersused.count()):
            name = self.list_playersused.item(x).text()
            self.cur.execute('SELECT Value from Stats WHERE Player = "' + name + '"')
            a = self.cur.fetchone()
            self.value = self.value + int(a[0])
        self.label_ptsused.setText(str(self.value))
        self.label_ptsavail.setText(str(1000 - self.value))

    def openDialog(self):
        self.cur.execute("SELECT Name from Teams")
        self.teams = self.cur.fetchall()
        print(self.teams)
        OpDialog = QtWidgets.QDialog()
        ui = Ui_OpDialog()
        ui.setupUi(OpDialog)
        for x in self.teams:
            ui.comboBox.addItem(x[0])
        OpDialog.show()
        rs = OpDialog.exec_()
        if rs == QtWidgets.QDialog.Accepted:
            self.label_teamname.setText(ui.comboBox.currentText())
            self.cur.execute('SELECT Players from Teams WHERE Name = "' + ui.comboBox.currentText() + '"')
            self.players = self.cur.fetchone()
            self.players = self.players[0].split(",", 11)
            del self.players[11]
            print(self.players)
            self.list_playersused.clear()
            for x in self.players:
                self.list_playersused.addItem(x)
            # enable radio buttons
            self.radio_bat.setEnabled(True)
            self.radio_bat.setChecked(True)
            self.radio_bow.setEnabled(True)
            self.radio_ar.setEnabled(True)
            self.radio_wk.setEnabled(True)
            # calling radio function
            self.radiofuction()
            self.listPopulate()
            self.pointsUsedFunction()

    def evalDialog(self):
        self.cur.execute("SELECT Name from Teams")
        self.teams = self.cur.fetchall()
        print(self.teams)
        EvalDlg = QtWidgets.QDialog()
        ui = Ui_EvalDlg()
        ui.setupUi(EvalDlg)
        ui.teamComboBox.addItem("Select Team")
        ui.matchComboBox.addItem("Select Match")
        for x in self.teams:
            ui.teamComboBox.addItem(x[0])
        ui.matchComboBox.addItem("Match 1")
        ui.matchComboBox.addItem("Match 2")
        ui.matchComboBox.addItem("Match 3")
        EvalDlg.show()
        EvalDlg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Your Selections"))
        self.label_6.setText(_translate("MainWindow", "Batsmen (BAT)"))
        self.label_batsmen.setText(_translate("MainWindow", "##"))
        self.label_8.setText(_translate("MainWindow", "Bowlers (BOW)"))
        self.label_bowlers.setText(_translate("MainWindow", "##"))
        self.label_5.setText(_translate("MainWindow", "Allrounders (AR)"))
        self.label_allrounders.setText(_translate("MainWindow", "##"))
        self.label_3.setText(_translate("MainWindow", "Wicket-keeper"))
        self.label_wicketkeeper.setText(_translate("MainWindow", "##"))
        self.label_4.setText(_translate("MainWindow", "Points Available"))
        self.label_ptsavail.setText(_translate("MainWindow", "##"))
        self.radio_bat.setText(_translate("MainWindow", "BAT"))
        self.radio_bow.setText(_translate("MainWindow", "BOW"))
        self.radio_ar.setText(_translate("MainWindow", "AR"))
        self.radio_wk.setText(_translate("MainWindow", "WK"))
        self.label_12.setText(_translate("MainWindow", "˃"))
        self.label_11.setText(_translate("MainWindow", "Points Used"))
        self.label_ptsused.setText(_translate("MainWindow", "##"))
        self.label_7.setText(_translate("MainWindow", "Team Name"))
        self.label_teamname.setText(_translate("MainWindow", "Displayed Here"))
        self.menuManage_Teams.setTitle(_translate("MainWindow", "Manage Teams"))
        self.actionNEW_Team.setText(_translate("MainWindow", "NEW Team"))
        self.actionNEW_Team.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOPEN_Team.setText(_translate("MainWindow", "OPEN Team"))
        self.actionOPEN_Team.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionEDIT_Team.setText(_translate("MainWindow", "SAVE Team"))
        self.actionEDIT_Team.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionEVALUATE_Team.setText(_translate("MainWindow", "EVALUATE Team"))
        self.actionEVALUATE_Team.setShortcut(_translate("MainWindow", "Ctrl+E"))


class Ui_OpDialog(object):
    def setupUi(self, OpDialog):
        OpDialog.setObjectName("OpDialog")
        OpDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        OpDialog.resize(230, 140)
        OpDialog.setMinimumSize(QtCore.QSize(230, 140))
        OpDialog.setMaximumSize(QtCore.QSize(230, 140))
        self.verticalLayout = QtWidgets.QVBoxLayout(OpDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(209, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(OpDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(OpDialog)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(OpDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OpDialog)
        self.buttonBox.accepted.connect(OpDialog.accept)
        self.buttonBox.rejected.connect(OpDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OpDialog)

        OpDialog.setWindowTitle("Open Team")

    def retranslateUi(self, OpDialog):
        _translate = QtCore.QCoreApplication.translate
        OpDialog.setWindowTitle(_translate("OpDialog", "Dialog"))
        self.label.setText(_translate("OpDialog", "Select the Team to Open"))


class Ui_EvalDlg(object):
    def setupUi(self, EvalDlg):
        EvalDlg.setObjectName("EvalDlg")
        EvalDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        EvalDlg.resize(550, 440)
        EvalDlg.setMinimumSize(QtCore.QSize(550, 440))
        EvalDlg.setMaximumSize(QtCore.QSize(550, 440))
        EvalDlg.setAutoFillBackground(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(EvalDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(EvalDlg)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.teamComboBox = QtWidgets.QComboBox(EvalDlg)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.teamComboBox.setFont(font)
        self.teamComboBox.setObjectName("teamComboBox")
        self.horizontalLayout.addWidget(self.teamComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.matchComboBox = QtWidgets.QComboBox(EvalDlg)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.matchComboBox.setFont(font)
        self.matchComboBox.setObjectName("matchComboBox")
        self.horizontalLayout.addWidget(self.matchComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(EvalDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(EvalDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(EvalDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_evalPoints = QtWidgets.QLabel(EvalDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_evalPoints.sizePolicy().hasHeightForWidth())
        self.label_evalPoints.setSizePolicy(sizePolicy)
        self.label_evalPoints.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_evalPoints.setFont(font)
        self.label_evalPoints.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_evalPoints.setObjectName("label_evalPoints")
        self.horizontalLayout_2.addWidget(self.label_evalPoints)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.tableWidget = QtWidgets.QTableWidget(EvalDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(2)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(11)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btnCalcScore = QtWidgets.QPushButton(EvalDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCalcScore.sizePolicy().hasHeightForWidth())
        self.btnCalcScore.setSizePolicy(sizePolicy)
        self.btnCalcScore.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.btnCalcScore.setFont(font)
        self.btnCalcScore.setDefault(False)
        self.btnCalcScore.setFlat(False)
        self.btnCalcScore.setObjectName("btnCalcScore")
        self.horizontalLayout_3.addWidget(self.btnCalcScore)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(EvalDlg)
        QtCore.QMetaObject.connectSlotsByName(EvalDlg)

        EvalDlg.setWindowTitle("Evaluate Score")

        # connection with database
        self.db = sqlite3.connect("Cricket.db")
        self.cur = self.db.cursor()

        self.label_evalPoints.setStyleSheet('color: blue')
        self.tableWidget.setStyleSheet('color: green')
        self.teamComboBox.activated.connect(self.tablePopulate)
        self.btnCalcScore.clicked.connect(self.evalScore)

    def evalScore(self):
        total = 0
        if self.teamComboBox.currentText() != "Select Team" and self.matchComboBox.currentText() != "Select Match":
            for x in range(self.tableWidget.rowCount()):
                self.cur.execute(
                    'SELECT Scored from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                scored = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT Faced from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                faced = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT Fours from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                fours = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT Sixes from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                sixes = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT Bowled from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                bowled = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT Maiden from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                maiden = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT Given from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                given = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT Wkts from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                wkts = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT Catches from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                catches = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT Stumping from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                stumping = int((self.cur.fetchone())[0])
                self.cur.execute(
                    'SELECT RunOut from Match1 WHERE Player = "' + self.tableWidget.item(x, 0).text() + '"')
                runout = int((self.cur.fetchone())[0])

                # score calculation
                score = scored / 2  # 1 point for 2 runs scored 
                if score >= 50: score += 5  # Additional 5 points for half century
                if score >= 100: score += 10  # Additional 10 points for century
                if scored > 0: sr = scored * 100 / faced  # strike rate
                if sr >= 80 and sr < 100: score += 2  # 2 points for strike rate (runs/balls faced) of 80-100
                if sr >= 100: score += 4  # Additional 4 points for strike rate>100 
                score += fours  # 1 point for hitting a boundary (four)
                score += 2 * sixes  # 2 points for over boundary (six)
                score += wkts * 10  # 10 points for each wicket
                if wkts >= 3: score += 5  # Additional 5 points for three wickets per innings
                if wkts >= 5: score += 10  # Additional 10 points for 5 wickets or more in innings
                if bowled > 0: er = scored / bowled  # economy rate
                if er <= 2: score += 1  # 4 points for economy rate (runs given per over) between 3.5 and 4.5
                if er > 2 and er <= 3.5: score += 7  # 7  points for economy rate between 2 and 3.5 
                if er > 3.5 and er <= 4.5: score += 4  # 10 points for economy rate less than 2 
                score += catches * 10  # 10 points each for catch
                score += stumping * 10  # 10 points each for stumping
                score += runout * 10  # 10 points each for run out
                self.tableWidget.setItem(x, 1, QtWidgets.QTableWidgetItem(str(score)))
                total += score
                self.label_evalPoints.setText(str(total))
        else:
            print('Either Team or Match is not selected')

    def tablePopulate(self):
        self.tableWidget.clear()
        self.label_evalPoints.setText("--")
        if self.teamComboBox.currentText() != "Select Team":
            self.cur.execute('SELECT Players from Teams WHERE Name = "' + self.teamComboBox.currentText() + '"')
            self.players = self.cur.fetchone()
            self.players = self.players[0].split(",", 11)
            del self.players[11]
            print(self.players)
            y = 0
            for x in self.players:
                self.tableWidget.setItem(y, 0, QtWidgets.QTableWidgetItem(x))
                y = y + 1
        else:
            self.tableWidget.clear()

    def retranslateUi(self, EvalDlg):
        _translate = QtCore.QCoreApplication.translate
        EvalDlg.setWindowTitle(_translate("EvalDlg", "Dialog"))
        self.label.setText(_translate("EvalDlg", "Evaluate the performance of Your Fantasy Team"))
        self.label_2.setText(_translate("EvalDlg", "Players"))
        self.label_3.setText(_translate("EvalDlg", "Points"))
        self.label_evalPoints.setText(_translate("EvalDlg", "--"))
        self.tableWidget.setSortingEnabled(False)
        self.btnCalcScore.setText(_translate("EvalDlg", "Calculate Score"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
